[package]

name = "ecc"
description = "An elliptic curve arithmetic and cryptography library."
version = "0.0.5"
authors = ["Brendan Mc. <brendanmcmillion@gmail.com>"]
license = "MIT"

[dependencies.num]
version = "0.0.5"
